name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 161.35.15.35
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            sudo rm -rf /var/www/frontend/*
            scp -r ./build/* /var/www/frontend
            sudo systemctl restart nginx
